### PR TITLE
Expense tracker app using flutter added

### PR DESCRIPTION
**Pull request by rohansen856**

### CODE REVIEW

**Comment by rohansen856** [comment]
This is corresponding to the issue #171. Thank you.

**Comment by Evgenii-Bazhaov** [comment]
@rohansen856 Are you uploading a zip file, please add files inside the folders only

**Comment by rohansen856** [comment]
@Evgenii-Bazhaov i have done all the changes and pushed it under "hisaab" folder. thank you.

**Comment by Evgenii-Bazhaov** [comment]
Hi👋, @rohansen856  can you please up-vote for him in devfest ai challenge. Please click the link below and claim bonus to support. Thanks 
➡️ https://devfest.ai/nocode-leaderboard/cm1auef9p000870ebzxkjhl73?claim=true

**Pull request merged**
